// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZCVei-N7fQvBx4sS1nLwzO8WThm3Jhoo',
    appId: '1:274785623628:web:a4b644fbcd178718735ee9',
    messagingSenderId: '274785623628',
    projectId: 'e-shop-ca9d4',
    authDomain: 'e-shop-ca9d4.firebaseapp.com',
    storageBucket: 'e-shop-ca9d4.appspot.com',
    measurementId: 'G-T3CCE7GQM0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCFGdgLukK9F4H_2f8gmV0W8_AhhtET8A',
    appId: '1:274785623628:android:577618311b6d8392735ee9',
    messagingSenderId: '274785623628',
    projectId: 'e-shop-ca9d4',
    storageBucket: 'e-shop-ca9d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUe2uK5eqI6fHUCBXgOgquf0aeud-4stM',
    appId: '1:274785623628:ios:f29747a428765185735ee9',
    messagingSenderId: '274785623628',
    projectId: 'e-shop-ca9d4',
    storageBucket: 'e-shop-ca9d4.appspot.com',
    iosBundleId: 'com.example.eApp',
  );
}
